Update before Deploy (#51)
* Update before Deploy
* Ignore `flyctl deploy` return code

diff --git a/.github/workflows/daily.yml b/.github/workflows/daily.yml
--- a/.github/workflows/daily.yml
+++ b/.github/workflows/daily.yml
@@ -116,6 +116,14 @@ jobs:
         git push
         popd
 
+    - name: Upload SQLite file to storage
+      run: |
+        set -Eeuxo pipefail
+
+        # gzip: less compact and slower than brotli, but more likely to already be installed on user's machines.
+        pigz build/Marktstammdatenregister.db
+        rclone copy --include Marktstammdatenregister.db.gz build/ 'wasabi:mastr-backup' --config build/rclone.conf
+
     - name: Deploy
       run: |
         set -Eeuxo pipefail
@@ -124,12 +132,5 @@ jobs:
         brotli --keep -4 --output=build/Marktstammdatenregister.db.br build/Marktstammdatenregister.db
         ls -lh build/Marktstammdatenregister.db.br
 
-        flyctl deploy . --config build/fly.toml --dockerfile build/Dockerfile --wait-timeout 120
-
-    - name: Upload SQLite file to storage
-      run: |
-        set -Eeuxo pipefail
-
-        # gzip: less compact and slower than brotli, but more likely to already be installed on user's machines.
-        pigz build/Marktstammdatenregister.db
-        rclone copy --include Marktstammdatenregister.db.gz build/ 'wasabi:mastr-backup' --config build/rclone.conf
+        # flyctl deploy fails consistently even though the deployment succeeds. Ignore the error code.
+        flyctl deploy . --config build/fly.toml --dockerfile build/Dockerfile --wait-timeout 120 || true
